{
    'name': 'Bảng lương Việt Nam',
    'version': '18.0.1.0.0',
    'category': 'Human Resources/Payroll',
    'summary': 'BHXH, thuế TNCN lũy tiến 7 bậc, giảm trừ gia cảnh, gross-up',
    'description': """
Requires Odoo Enterprise: hr_payroll, hr_work_entry_contract_enterprise.
    """,
    'author': 'SHT',
    'depends': ['hr_payroll', 'hr_work_entry_contract_enterprise', 'sht_hr_base', 'sht_hr_contract', 'sht_hr_reward_discipline', 'mail'],
    'data': [
        'security/hr_payroll_vietnam_security.xml',
        'security/ir.model.access.csv',
        'data/insurance_config_2024.xml',
        'data/pit_brackets_2024.xml',
        'data/personal_deduction.xml',
        'data/allowance_limits.xml',
        'data/hr_rule_parameters_vn.xml',
        'data/salary_structure_vn.xml',
        'data/salary_structure_probation.xml',
        'data/salary_structure_parttime.xml',
        'data/salary_structure_bonus.xml',
        'data/salary_structure_fixednet.xml',
        'data/reward_input_type.xml',
        'data/vn_public_holidays.xml',
        'data/vn_work_schedules.xml',
        'views/hr_employee_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_vn_config_views.xml',
        'views/hr_vn_dependent_views.xml',
        'views/hr_vn_payroll_config_views.xml',
        'views/hr_payroll_structure_views.xml',
        'wizard/payroll_simulate_views.xml',
        'wizard/payroll_bank_export_views.xml',
        'wizard/pit_annual_settlement_views.xml',
        'views/hr_payslip_run_views.xml',
        'views/hr_payroll_config_vn_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
