from . import vn_tax_engine
from . import hr_employee
from . import hr_contract
from . import hr_vn_dependent
from . import hr_vn_insurance_config
from . import hr_vn_regional_wage
from . import hr_vn_pit_bracket
from . import hr_vn_personal_deduction
from . import hr_vn_allowance_config
from . import hr_vn_payroll_config
from . import hr_payroll_structure
from . import hr_payslip_run
from . import hr_payslip
from . import hr_salary_rule
